# Generated by Django 3.1.3 on 2021-11-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20211105_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcuser',
            name='useremail',
        ),
        migrations.RemoveField(
            model_name='fcuser',
            name='username',
        ),
        migrations.AddField(
            model_name='fcuser',
            name='emp_id',
            field=models.IntegerField(null='True', verbose_name='직원 번호'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='fcuser',
            name='emp_name',
            field=models.CharField(max_length=32, null='True', verbose_name='직원 이름'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='fcuser',
            table='emp_list',
        ),
    ]
