# Generated by Django 3.2.9 on 2021-11-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20211116_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
