# Generated by Django 3.1.3 on 2021-11-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0004_alter_fcuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
