# Generated by Django 3.2.9 on 2021-12-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='상품코드')),
                ('loan_product_name', models.CharField(max_length=30, null='False', verbose_name='대출상품이름')),
            ],
            options={
                'verbose_name': '대출상품이름',
                'verbose_name_plural': '대출상품이름',
                'db_table': 'loan_product',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=32, null='True', verbose_name='직원 이름')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('content', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': '오늘의 할일',
                'verbose_name_plural': '오늘의 할일',
                'db_table': 'TodoList',
            },
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=32, null='True', verbose_name='직원 이름')),
                ('customer_id', models.IntegerField(default=12345678, verbose_name='고객번호')),
                ('customer_name', models.CharField(max_length=256, null='False', verbose_name='고객명')),
                ('loan_start_date', models.DateField(null='False', verbose_name='실행 예정일')),
                ('loan_product', models.CharField(max_length=30, null='True', verbose_name='대출상품')),
                ('loan_amount', models.IntegerField(null='True', verbose_name='대출금액')),
                ('loan_condition', models.CharField(max_length=10, null='True', verbose_name='상환조건')),
                ('description', models.TextField(verbose_name='메모')),
                ('phone_number', models.CharField(max_length=13, null=True, verbose_name='핸드폰번호')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('current_process_id', models.IntegerField(default=1, verbose_name='현재 진행 척도')),
            ],
            options={
                'verbose_name': '업무목록',
                'verbose_name_plural': '업무목록',
                'db_table': 'WorkSheet',
            },
        ),
        migrations.CreateModel(
            name='LoanProcess',
            fields=[
                ('loan_product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='board.loanproduct')),
                ('loan_process_level', models.IntegerField()),
                ('loan_process_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '대출업무 진행단계',
                'verbose_name_plural': '대출업무 진행단계',
                'db_table': 'loan_process',
                'unique_together': {('loan_product', 'loan_process_level')},
            },
        ),
    ]
