# Generated by Django 3.2.9 on 2021-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='loan_condition',
            field=models.CharField(max_length=10, null='True', verbose_name='상환조건'),
        ),
    ]
