# Generated by Django 3.2.9 on 2021-12-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='loan_condition',
            field=models.BooleanField(default=False),
        ),
    ]
