# Generated by Django 3.2.9 on 2021-11-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211116_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(default=12345678, verbose_name='고객번호')),
                ('customer_name', models.CharField(max_length=256, null='False', verbose_name='고객명')),
                ('loan_amount', models.IntegerField(null='True', verbose_name='대출금액\x1d')),
                ('description', models.TextField(verbose_name='메모')),
                ('stock', models.IntegerField(verbose_name='재고')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '업무목록',
                'verbose_name_plural': '업무목록',
                'db_table': 'WorkSheet',
            },
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
