# Generated by Django 3.2.9 on 2021-12-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_worksheet_loan_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='current_process_id',
            field=models.IntegerField(default=1, verbose_name='현재 진행 척도'),
        ),
    ]
