# Generated by Django 3.2.9 on 2021-11-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20211119_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='stock',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='loan_product',
            field=models.CharField(max_length=30, null='True', verbose_name='대출상품\x1d'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, verbose_name='핸드폰번호'),
        ),
    ]
