# Generated by Django 3.2.9 on 2021-12-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_worksheet_current_process_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process2',
        ),
    ]
