# Generated by Django 3.2.9 on 2021-12-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_delete_process2'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_product_name', models.CharField(max_length=30, null='False', verbose_name='대출상품이름')),
            ],
            options={
                'verbose_name': '대출상품이름',
                'verbose_name_plural': '대출상품이름',
                'db_table': 'loan_product',
            },
        ),
    ]
