# Generated by Django 3.2.9 on 2021-11-22 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0004_alter_fcuser_id'),
        ('board', '0004_auto_20211119_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='emp_name',
            field=models.ForeignKey(
                null='True',
                on_delete=django.db.models.deletion.CASCADE,
                to='fcuser.fcuser',
                verbose_name='작성자'),
            preserve_default='True',
        ),
    ]
