# Generated by Django 3.2.9 on 2021-12-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_loan_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id2', models.IntegerField(null='False', verbose_name='상품코드')),
                ('loan_product_name', models.CharField(max_length=30, null='False', verbose_name='대출상품이름')),
            ],
            options={
                'verbose_name': '대출상품이름2',
                'verbose_name_plural': '대출상품이름2',
                'db_table': 'loan_product2',
            },
        ),
    ]
