# Generated by Django 3.1.3 on 2021-11-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_worksheet_emp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='loan_start_date',
            field=models.DateField(null='False', verbose_name='실행 예정일'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='emp_name',
            field=models.CharField(max_length=32, null='True', verbose_name='직원 이름'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
