# Generated by Django 3.1.3 on 2021-12-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20211130_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_product', models.CharField(max_length=30, null='True', verbose_name='대출상품')),
                ('process_index', models.IntegerField(null='True', verbose_name='진행순번')),
                ('process_step', models.CharField(max_length=30, null='True', verbose_name='진행단계')),
            ],
            options={
                'verbose_name': '진행척도관리',
                'verbose_name_plural': '진행척도관리',
                'db_table': 'Process',
            },
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='loan_amount',
            field=models.IntegerField(null='True', verbose_name='대출금액'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='loan_product',
            field=models.CharField(max_length=30, null='True', verbose_name='대출상품'),
        ),
    ]
